CREATE TABLE [dbo].[dim_date] (
    [dim_date_key]         INT          NULL,
    [calendar_date]        DATETIME     NOT NULL,
    [cal_day_in_week]      VARCHAR (3)  NULL,
    [cal_day_in_week_no]   INT          NULL,
    [cal_day_in_month]     INT          NULL,
    [cal_day_in_year]      INT          NULL,
    [cal_week_in_year]     INT          NULL,
    [cal_month_no]         INT          NULL,
    [cal_month]            INT          NULL,
    [cal_month_name]       VARCHAR (7)  NULL,
    [cal_month_first_date] DATETIME     NULL,
    [cal_month_last_date]  DATETIME     NULL,
    [cal_quarter_no]       INT          NULL,
    [cal_quarter]          INT          NULL,
    [cal_quarter_display]  VARCHAR (2)  NULL,
    [cal_year]             INT          NULL,
    [financial_date]       DATETIME     NULL,
    [fin_day_in_week]      VARCHAR (3)  NULL,
    [fin_day_in_week_no]   INT          NULL,
    [fin_day_in_month]     INT          NULL,
    [fin_day_in_year]      INT          NULL,
    [fin_week_in_month]    INT          NULL,
    [fin_week_in_year]     INT          NULL,
    [fin_month_no]         INT          NULL,
    [fin_month]            INT          NULL,
    [fin_month_name]       VARCHAR (7)  NULL,
    [fin_period]           VARCHAR (20) NULL,
    [fin_quarter_no]       INT          NULL,
    [fin_quarter]          INT          NULL,
    [fin_quarter_display]  VARCHAR (2)  NULL,
    [fin_year]             INT          NULL,
    [fin_year_display]     VARCHAR (6)  NULL,
    [current_cal_day]      VARCHAR (8)  NULL,
    [current_cal_week]     VARCHAR (8)  NULL,
    [current_cal_month]    VARCHAR (8)  NULL,
    [current_cal_year]     VARCHAR (8)  NULL,
    [current_cal_mtd]      VARCHAR (8)  NULL,
    [current_cal_ytd]      VARCHAR (8)  NULL,
    [moving_cal_year]      VARCHAR (8)  NULL,
    [current_fin_day]      VARCHAR (8)  NULL,
    [current_fin_week]     VARCHAR (8)  NULL,
    [current_fin_month]    VARCHAR (8)  NULL,
    [current_fin_quarter]  VARCHAR (8)  NULL,
    [current_fin_year]     VARCHAR (8)  NULL,
    [current_fin_mtd]      VARCHAR (8)  NULL,
    [current_fin_ytd]      VARCHAR (8)  NULL,
    [moving_fin_quarter]   VARCHAR (8)  NULL,
    [moving_fin_year]      VARCHAR (8)  NULL,
    [week_start_date]      DATETIME     NULL,
    [week_end_date]        DATETIME     NULL,
    [week_day_flag]        VARCHAR (1)  NULL,
    [week_end_flag]        VARCHAR (1)  NULL,
    [working_day_flag]     VARCHAR (1)  NULL,
    [holiday_flag]         VARCHAR (1)  NULL,
    [holiday_desc]         VARCHAR (64) NULL,
    [trading_day_flag]     VARCHAR (1)  NULL,
    [trading_days_in_mth]  INT          NULL,
    [trading_days_so_far]  INT          NULL,
    [trading_day_offset]   INT          NULL,
    [day_offset]           INT          NULL,
    [month_offset]         INT          NULL,
    [year_offset]          INT          NULL,
    [fn1_pay_period]       VARCHAR (26) NULL,
    [fn1_from_date]        DATETIME     NULL,
    [fn1_to_date]          DATETIME     NULL,
    [fn2_pay_period]       VARCHAR (26) NULL,
    [fn2_from_date]        DATETIME     NULL,
    [fn2_to_date]          DATETIME     NULL,
    [dss_update_time]      DATETIME     NULL,
    [fin_year_offset]      INT          NULL,
    CONSTRAINT [PK_dim_date] PRIMARY KEY CLUSTERED ([calendar_date] ASC) WITH (FILLFACTOR = 90)
);




GO
CREATE NONCLUSTERED INDEX [IX_date]
    ON [dbo].[dim_date]([calendar_date] ASC) WITH (FILLFACTOR = 90);

