CREATE TABLE [bureau].[TLocation] (
    [loc_id]                 INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [loc_description]        VARCHAR (200) NOT NULL,
    [rc_code]                VARCHAR (10)  NOT NULL,
    [trendcare_code]         VARCHAR (10)  NULL,
    [hospital_lk_id]         INT           NULL,
    [sort_order]             INT           NULL,
    [create_dttm]            DATETIME      CONSTRAINT [DF_Location_create_dttm] DEFAULT (getdate()) NOT NULL,
    [create_user]            VARCHAR (50)  CONSTRAINT [DF_Location_create_user] DEFAULT ('bureau_system') NOT NULL,
    [modif_dttm]             DATETIME      CONSTRAINT [DF_Location_modif_dttm] DEFAULT (getdate()) NOT NULL,
    [modif_user]             VARCHAR (50)  CONSTRAINT [DF_Location_modif_user] DEFAULT ('bureau_system') NOT NULL,
    [is_deleted]             SMALLINT      CONSTRAINT [DF_Location_is_deleted] DEFAULT ((0)) NOT NULL,
    [day_start]              VARCHAR (5)   NULL,
    [evening_start]          VARCHAR (5)   NULL,
    [night_start]            VARCHAR (5)   NULL,
    [E_Coord]                INT           NULL,
    [E_Orientee]             INT           NULL,
    [E_RN]                   INT           NULL,
    [E_EN]                   INT           NULL,
    [E_HCA]                  INT           NULL,
    [N_Coord]                INT           NULL,
    [N_Orientee]             INT           NULL,
    [N_RN]                   INT           NULL,
    [N_EN]                   INT           NULL,
    [N_HCA]                  INT           NULL,
    [D_Coord]                INT           NULL,
    [D_Orientee]             INT           NULL,
    [D_RN]                   INT           NULL,
    [D_EN]                   INT           NULL,
    [D_HCA]                  INT           NULL,
    [D_CNM]                  INT           NULL,
    [config_rpt_colour]      VARCHAR (50)  NULL,
    [config_rpt_group]       VARCHAR (50)  NULL,
    [config_rpt_group_order] INT           NULL,
    [config_rpt_font_colour] VARCHAR (50)  NULL,
    CONSTRAINT [PK_Location] PRIMARY KEY CLUSTERED ([loc_id] ASC) WITH (FILLFACTOR = 90)
);

